-- AlterEnum: add VENDOR_SELL_PRICE and MARGIN_SPLIT to ConsignmentType
ALTER TYPE "ConsignmentType" ADD VALUE IF NOT EXISTS 'VENDOR_SELL_PRICE';
ALTER TYPE "ConsignmentType" ADD VALUE IF NOT EXISTS 'MARGIN_SPLIT';
